const images = ["../../assets/images/dnd/fr1.jpg",
    "../../assets/images/dnd/fr2.jpg",
    "../../assets/images/dnd/fr3.jpg",
    "../../assets/images/dnd/fr4.jpg",
    "../../assets/images/dnd/fr5.jpg",
    "../../assets/images/dnd/fr6.jpg",
    "../../assets/images/dnd/fr7.jpg",
    "../../assets/images/dnd/fr8.jpg",
    "../../assets/images/dnd/fr9.jpg",
    "../../assets/images/dnd/fr10.jpg",
    "../../assets/images/dnd/fr11.jpg",
    "../../assets/images/dnd/fr12.jpg",
    "../../assets/images/dnd/fr13.jpg",
    "../../assets/images/dnd/fr14.jpg",
    "../../assets/images/dnd/fr15.jpg",
    "../../assets/images/dnd/fr16.jpg",
    "../../assets/images/dnd/fr17.jpg",
    "../../assets/images/dnd/fr18.jpg",
    "../../assets/images/dnd/fr19.jpg",
    "../../assets/images/dnd/fr20.jpg",
    "../../assets/images/dnd/fr21.jpg",
    "../../assets/images/dnd/fr20.jpg",
    "../../assets/images/dnd/fr23.jpg",
    "../../assets/images/dnd/fr24.jpg",
    "../../assets/images/dnd/fr20.jpg",
    "../../assets/images/dnd/fr26.jpg",
    "../../assets/images/dnd/fr27.jpg",
    "../../assets/images/dnd/fr28.jpg",
    "../../assets/images/dnd/fr29.jpg"]; 

export default images;

//  {
//     fr1,
//     fr10,
//     fr11,
//     fr12,
//     fr13,
//     fr14,
//     fr15,
//     fr16,
//     fr17,
//     fr18,
//     fr19,
//     fr2,
//     fr20,
//     fr21,
//     fr22,
//     fr23,
//     fr24,
//     fr25,
//     fr26,
//     fr27,
//     fr28,
//     fr29,
//     fr3,
//     fr4,
//     fr5,
//     fr6,
//     fr7,
//     fr8,
//     fr9,
// };
// export default images